version: "3.7"
services:
  web:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
    depends_on: 
      - mongodb
  mongodb:
    image: mongo:4.4.4
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: francodev
    volumes:
      - data:/data/db
volumes:
  data:
  node_modules:
